"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _auth_login_screen from './auth-login-screen.bones.json'
import _auth_register_screen from './auth-register-screen.bones.json'
import _projects_loading_screen from './projects-loading-screen.bones.json'
import _settings_loading_screen from './settings-loading-screen.bones.json'
import _editor_loading_screen from './editor-loading-screen.bones.json'

registerBones({
  "auth-login-screen": _auth_login_screen,
  "auth-register-screen": _auth_register_screen,
  "projects-loading-screen": _projects_loading_screen,
  "settings-loading-screen": _settings_loading_screen,
  "editor-loading-screen": _editor_loading_screen,
})
